# Mitch Gavars
# Lab07 - Makefile
# 02/26/19

all: primes2 counte matrix-sum time

primes2: is_prime.s primes2.c
	gcc primes2.c is_prime.s -o primes 2

counte: counte.s counte.c
	gcc counte.c counte.s -o counte

matrix-sum: matrix-sum.s matrix-sum.c
	gcc matrix-sum.s matrix-sum.c -o matrix-sum

time: time.s time.c
	gcc time.s time.c -o time
